l1_4:
	g++ -Wall -Wextra l1_4.cpp -std=c++14

l3_3:
	g++ -Wall -Wextra l3_3.cpp -std=c++14

l4_3:
	g++ -Wall -Wextra l4_3.cpp -std=c++14

l6_2:
	g++ -Wall -Wextra l6_2.cpp -std=c++14

l6_5:
	g++ -Wall -Wextra l6_5.cpp -std=c++14

l6_6:
	g++ -Wall -Wextra L6_6.cpp -std=c++14

l6_8:
	g++ -Wall -Wextra l6_8.cpp -std=c++14

l6_9:
	g++ -Wall -Wextra l6_9.cpp -std=c++14

l6_10:
	g++ -Wall -Wextra l6_10.cpp -std=c++14

l6_13:
	g++ -Wall -Wextra l6_13.cpp -std=c++14

l6_15:
	g++ -Wall -Wextra l6_15.cpp -std=c++14
run:
	./a.out

clean: 
	rm -rf a.out